# AWS CodeBuild pipeline
version: 0.2
phases:  
  pre_build:
    commands:
      - echo deployment started on `date`
      - echo syncing content 
      - aws s3 sync ./www/ s3://studionotesapp.xyz
  build:
    commands:
      - echo invalidating cloudfront cache
      # aws cloudfront create-invalidation --distribution-id ##### --paths "/*"
  post_build:
     commands:
      - echo Build completed on `date`

